apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJjR1YwY205MlpIWTZaMmh3WHpWblFuVTBabWh3UkhKelJYbG1OWGRRTTBsck1XdE5SWE5pVWpoYU5qUTVWVFZQWVE9PSIKCQl9Cgl9Cn0K
type: kubernetes.io/dockerconfigjson
